apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/secret.yaml
  - postgres/configmap.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  
  - nopcommerce/pvc.yaml
  - nopcommerce/deployment.yaml
  - nopcommerce/service.yaml